[build]
  functions = "functions"
  publish = "."

[dev]
  functions = "functions"

[[redirects]]
  from = "https://www.ern-cicek.com.tr/*"
  to = "https://ern-cicek.com.tr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://ern-cicek.com.tr/*"
  to = "https://ern-cicek.com.tr/:splat"
  status = 301
  force = true
