name = "ern-site"
main = "src/index.js"
compatibility_date = "2025-12-02"

[vars]
GITHUB_OWNER = "amtbrs-03"
GITHUB_REPO = "AMTBRS"
GITHUB_BRANCH = "site-release"
TO_EMAIL = "amtbrs@icloud.com"
FROM_EMAIL = "no-reply@ern-cicek.com.tr"

routes = []
# You can later add a custom route like:
# routes = [
#   { pattern = "api.ern-cicek.com.tr/send-order", custom_domain = true }
# ]
